name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Set this to your default branch name

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1"
          bundler-cache: false # We'll handle caching manually

      - name: Update Gemfile.lock
        run: |
          bundle config set --local path 'vendor/bundle'
          bundle config set --local frozen false
          bundle install
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add Gemfile.lock
          git commit -m "Update Gemfile.lock" || echo "No changes to commit"
          git push

      - name: Build the site
        run: bundle exec jekyll build
        env:
          JEKYLL_ENV: production

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
