name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Set this to your default branch name

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2' # This version should be compatible with your Bundler
          bundler-cache: true # This will install and cache your Ruby dependencies
      
      - name: Build and Deploy
        uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          jekyll_src: '.'  # Change this if your Jekyll source is not in the root
          gem_src: '.'     # Change this if your Gemfile is not in the root